### ISSUE TITLE
Improvements to Heartrate

### ISSUE THREAD

**Issue by Dikay900** [Dikay900/Gadgetbridge#2]
- [X] Freeyourgadget/Gadgetbridge#1173 
- [ ] Freeyourgadget/Gadgetbridge#372 | Freeyourgadget/Gadgetbridge#1247
- [ ] Freeyourgadget/Gadgetbridge#377: Display heart rate in notification
- [ ] Freeyourgadget/Gadgetbridge#379: continuous heart rate measurements and recording
- [ ] Freeyourgadget/Gadgetbridge#380
- [ ] Freeyourgadget/Gadgetbridge#381
- [ ] Freeyourgadget/Gadgetbridge#382

<hr/>

- [X] Skip out of line or dead like detections ( < 40 ? Casual HR monitoring) - https://github.com/Freeyourgadget/Gadgetbridge/blob/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/HeartRateUtils.java
- [ ] Retry to read HR if first try was not successful
- [ ] Mi Band 3 HR support fully supported in GB?
